{% set name = "JSBSim" %}
{% set version = "0.99.61" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 216458f880d6f0fa5da3af6a10d77e0b94a4c107e18900cd30e292402bced1f9

build:
  number: 0
  skip: True  # [py<36]
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - cython
  run:
    - python
    - numpy

test:
  imports:
    - jsbsim
  commands:
    - python -c "import jsbsim;fdm=jsbsim.FGFDMExec('.', None);print(jsbsim.FGAircraft.__doc__)"

about:
  home: https://github.com/JSBSim-Team/jsbsim
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE.txt
  summary: 'An open source flight dynamics & control software library'
  description: |
    JSBSim is a multi-platform, general purpose object-oriented Flight Dynamics
    Model (FDM) written in C++. The FDM is essentially the physics & math model
    that defines the movement of an aircraft, rocket, etc., under the forces and
    moments applied to it using the various control mechanisms and from the
    forces of nature. JSBSim can be run in a standalone batch mode flight
    simulator (no graphical displays) for testing and study, or integrated with
    FlightGear <https://www.flightgear.org> or other flight simulator.
extra:
  recipe-maintainers:
    - bcoconni
